### PR TITLE
Trackit Console UI Update

### PR DESCRIPTION
**Pull request by hug33k**

### CODE REVIEW

**Comment by alexis-ld** [comment]
@hug33k : 

There's quite some things to change before merging.
Here's a list : 


1./ On the home page, the monthly bill endpoint is not found (404). I tried after merging the dev branch from the main trackit repo into your branch but it's sill not found on the API. Can you please troubleshoot this issue and make sure every endpoint is working for the next PR ?

screen shot 2017-09-21 at 17 05 04

2./ On the Monitor -> Ressources view
- The three red badges at the top to enable/disable providers look good but they are waaaayy too big. (see screenshot).
-Also please move the EC2 Instances panel to the top somehow, as it's not really visible being beneath the table.

fireshot capture 52 - trackit io - http___localhost_8000_ _app_resources

3./ Can you comment the Automate entry from the menu for now ? The cloudmover is not really functionnal for now so we won't display it for now.
Also since it gives us more space please remove the Optimize Dropdown and expose the two entries directly. The menu should be
HOME   MONITOR   MY RESOURCES   PREDICTION
We may change it again later but for now we'll do that.

**Review by alexis-ld — CHANGES_REQUESTED** [review]
Please check my previous comment for a list of required changes.

**Comment by hug33k** [comment]
@alexis-ld 

1 / In Progress

2 + 3 / Is it good like that ?
- Menu is now like that : `HOME | MONITOR | MY RESOURCES | PREDICTION`
- I moved the EC2 Instances panel to the top, before filters. It is only displayed when `AWS` is selected.
- Filters for providers are now smaller. Is it still too big ?

**Comment by alexis-ld** [comment]
@hug33k : Menu is good like that for now.
The badges are still very slightly too big but yes it is way better :).
Ping me when you're done with 1./ so I can review again.

**Comment by hug33k** [comment]
@alexis-ld 

1 / Fixed

**Comment by hug33k** [comment]
## TODO
- [x] TRAC-499 : Rename sections in Menu
- [x] TRAC-500 : Remove system metrics on My Resources section
- [x] TRAC-501 : Full size charts in Monitor > Utilization
- [x] TRAC-502 : Default AWS Cost Breakdown should be 30 days
- [x] TRAC-503 : Smaller badges in Monitor > Resources
- [x] TRAC-504 : Update User dropdown in Menu
- [x] TRAC-506 : Monthly bills are not showing correctly

**Comment by hug33k** [comment]
@alexis-ld 
Tasks `TRAC-[499|500|501|502|503|504|506]` are now done

**Comment by alexis-ld** [comment]
Thanks. Waiting for the react cleaning to be done  also please remerge the latest dev branch into this and I will approve :)

**Review by alexis-ld — APPROVED** [review]

**Pull request merged**
