### PR TITLE
S3 Buckets data

### PR DESCRIPTION
**Pull request by hug33k**
#TRAC-474 : Add table & chart for S3 Buckets data in Monitor > Resources > Storage
#TRAC-454 : Add dropdown to select tag for S3 buckets data

### CODE REVIEW

**Comment by alexis-ld** [comment]
@hug33k : 
The table is fine but we need to change the way we handle the charts.

You can't display a serie for each S3 bucket on the charts as most big accounts have a lot of buckets.

screen shot 2017-10-12 at 17 10 58

See, with medium accounts we don't even see the chart.

One solution would be to keep only the 20 buckets with the most transfers and only display those on the chart.
(if the limit of 20 is reached you display a closable Boostrap alert telling the user 'Only the 20 S3 buckets with the more transfers are displayed .... etc' so the user know some charts are missing) .

Also sometime the chart is totally bugged like this : 

screen shot 2017-10-12 at 17 15 00

You probably need to dispatch an event to fix it, I think you already did this on the home page at some point. :)

Thank you

**Review by alexis-ld — CHANGES_REQUESTED** [review]
See my comment for requested changes.

**Comment by hug33k** [comment]
Now, the chart only shows buckets that are listed above.
So now, when you change page, it will update the chart too.

**Comment by alexis-ld** [comment]
@hug33k : 
Displaying only the charts of the current page is a great idea ! :) it works nicely.

However I still have issues with the chart not being displayed properly.
I noticed it's when you wait a bit before opening the S3 tab, can you please fix this first thing tomorrow so we can finally merge this ? :p 

screen shot 2017-10-17 at 18 48 32

Thank you

**Comment by hug33k** [comment]
I added an `Event('resize')` that will be triggered when user is changing tab, from `Global` to `S3 Buckets` so the chart will be updated.

**Review by alexis-ld — APPROVED** [review]

**Pull request merged**
